import LoginImg from './login.jpg'
import Logo from './logo.png'
import Portrait from './portrait.jpg'
import SignupImg from './signupImg.png'
import Avatar from './avatar.png'
import PlaceHolderPostImg from './placeholder.jpg'
import AvatarUser from './avataruser.jpg'
import NoResultFound from './noResultFound.png'
import InitSearchImage from './initSearch.png'
export { NoResultFound, LoginImg, Logo, Portrait, SignupImg, Avatar, PlaceHolderPostImg, AvatarUser, InitSearchImage }